# Generated by Django 4.2.16 on 2024-09-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
