# Generated by Django 4.2.16 on 2024-09-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosApp', '0003_rename_categoria_game_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reseña',
            field=models.TextField(default='Sin reseña'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
    ]
