# Generated by Django 4.2.16 on 2025-07-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuegosApp', '0004_game_reseña_alter_game_plataforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reseña',
        ),
        migrations.AlterField(
            model_name='game',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
    ]
